### ISSUE TITLE
开发建议

### ISSUE THREAD

**Issue by yizhibaize1** [PandaChen1/God-Mode-#1]
建议使用其他其他方式写GUI，比如[Qt](https://github.com/qt/qt5)和[hummer](https://hummer.didi.cn/)，甚至VB（别用[electron](https://www.electronjs.org/zh/docs/latest/)就行）以避免报毒
如果追求美观就用[WinUI2或WinUI3](https://learn.microsoft.com/zh-cn/windows/apps/winui/)，整合进UWP
功能可以再多一些，也可以删除ie相关功能（~~谁没事用IE上网~~）
整合一些小工具（例如激活win&office等）
MMC有关功能可以拆分的更加详细
需要加上开源协议，推荐GPL，MIT也行

**Comment by PandaChen1** [comment]
你好！
感谢你的建议，我是一个 GitHub 小白，还请多指出问题
我想问一下开源协议是什么？

**Comment by PandaChen1** [comment]
> 建议使用其他其他方式写GUI，比如[Qt](https://github.com/qt/qt5)和[hummer](https://hummer.didi.cn/)，甚至VB（别用[electron](https://www.electronjs.org/zh/docs/latest/)就行）以避免报毒 如果追求美观就用[WinUI2或WinUI3](https://learn.microsoft.com/zh-cn/windows/apps/winui/)，整合进UWP 功能可以再多一些，也可以删除ie相关功能（~谁没事用IE上网~） 整合一些小工具（例如激活win&office等） MMC有关功能可以拆分的更加详细 需要加上开源协议，推荐GPL，MIT也行

你好！
感谢你的建议，我是一个 GitHub 小白，有一个问题想问一下：
开源协议是什么？

**Comment by gytxtx** [comment]
开源协议规定了你在使用开源软件时的权利和责任，也就是规定了你可以做什么，不可以做什么。开源协议虽然不一定具备法律效力，但是当涉及软件版权纠纷时，开源协议也是非常重要的证据之一。

简单的来说，开源协议就是将代码（项目）转化为开源软件的东西。开源许可基本上可以看作是开源依赖项的作者和使用服务的客户之间合法的绑定契约，约束的内容就是开源代码。开源协议往往会制定一些特定的条款，只有在满足这些条款的前提下，该软件才能用于商业分发。

对于准备编写一款开源软件的开发人员，也非常建议先了解一下当前最热门的开源许可协议，选择一个合适的开源许可协议来最大限度保护自己的软件权益。

引自：https://www.php.cn/faq/500997.html

**Comment by LAGQWQ** [comment]
> 建议使用其他其他方式写GUI，比如[Qt](https://github.com/qt/qt5)和[hummer](https://hummer.didi.cn/)，甚至VB（别用[electron](https://www.electronjs.org/zh/docs/latest/)就行）以避免报毒 如果追求美观就用[WinUI2或WinUI3](https://learn.microsoft.com/zh-cn/windows/apps/winui/)，整合进UWP 功能可以再多一些，也可以删除ie相关功能（~谁没事用IE上网~） 整合一些小工具（例如激活win&office等） MMC有关功能可以拆分的更加详细 需要加上开源协议，推荐GPL，MIT也行

你好！我是God Mode ++开发成员——`LAGSNES`！
God Mode ++不准备使用任何开源协议，我们希望每个人都可以使用**代码**而不忘标注作者，就像`Apache Lisence 2.0`那样！

**Comment by LAGQWQ** [comment]
> 建议使用其他其他方式写GUI，比如[Qt](https://github.com/qt/qt5)和[hummer](https://hummer.didi.cn/)，甚至VB（别用[electron](https://www.electronjs.org/zh/docs/latest/)就行）以避免报毒 如果追求美观就用[WinUI2或WinUI3](https://learn.microsoft.com/zh-cn/windows/apps/winui/)，整合进UWP 功能可以再多一些，也可以删除ie相关功能（~谁没事用IE上网~） 整合一些小工具（例如激活win&office等） MMC有关功能可以拆分的更加详细 需要加上开源协议，推荐GPL，MIT也行

你好！我是God Mode ++开发成员——`LAGSNES`！
God Mode ++不准备使用任何开源协议，我们希望每个人都可以使用**代码**而不忘标注作者，就像`Apache Lisence 2.0`那样！

**Comment by LAGQWQ** [comment]
> 建议使用其他其他方式写GUI，比如[Qt](https://github.com/qt/qt5)和[hummer](https://hummer.didi.cn/)，甚至VB（别用[electron](https://www.electronjs.org/zh/docs/latest/)就行）以避免报毒 如果追求美观就用[WinUI2或WinUI3](https://learn.microsoft.com/zh-cn/windows/apps/winui/)，整合进UWP 功能可以再多一些，也可以删除ie相关功能（~谁没事用IE上网~） 整合一些小工具（例如激活win&office等） MMC有关功能可以拆分的更加详细 需要加上开源协议，推荐GPL，MIT也行

你好！我是God Mode ++开发成员——`LAGSNES`！
God Mode ++不准备使用任何开源协议，我们希望每个人都可以使用**代码**而不忘标注作者，就像`Apache Lisence 2.0`那样！
